let wensen = [
  {
    "id": 1,
    "afbeelding": "",
    "titel": "Genoeg bankjes op het strand",
    "omschrijving": "Ik wil graag genoeg bankjes op het strand zodat ik lekker kan zitten en kijken naar hoe mijn kleinkinderen aan het spelen en dollen zijn op het strand. Eventueel zouden picknicktafels ook een goede optie zijn zodat we ook een plek hebben om ergens te zitten en te lunchen",
    "themas": ["Natuur", "Infrastructuur"],
    "ambassadeurs": 2,
    "helpers": 7,
    "steuners": 26,
  },
  {
    "id": 2,
    "afbeelding": "",
    "titel": "Bewakingscamera's rondom Strandeiland",
    "omschrijving": "In verband met veiligheid lijkt het ons fijn als er meerdere bewakingscamera's op Strandeiland zijn.",
    "themas": ["Veiligheid"],
    "ambassadeurs": 0,
    "helpers": 1,
    "steuners": 4,
  },
  {
    "id": 3,
    "afbeelding": "",
    "titel": "Buurthuis voor ouderen",
    "omschrijving": "Het zou fijn zijn als er een buurthuis komt voor ouderen (en jongeren?) om eenzaamheid te bestrijden. Op die manier hebben we contact met de bewoners van Strandeiland en kunnen we meer verbondenheid krijgen",
    "themas": ["Recreatie"],
    "ambassadeurs": 3,
    "helpers": 4,
    "steuners": 15,
  },
  {
    "id": 4,
    "afbeelding": "",
    "titel": "Kinderen leren milieu te beschermen",
    "omschrijving": "Een lesplan voor basisscholen, zodat jonge kinderen al leren om zwerfafval op te ruimen",
    "themas": ["Onderwijs", "Jeugd", "Milieu"],
    "ambassadeurs": 4,
    "helpers": 10,
    "steuners": 31,
  },
  {
    "id": 5,
    "afbeelding": "",
    "titel": "Kleine ondernemers",
    "omschrijving": "Het zou fijn zijn als er betaalbare winkelpanden komen zodat ook de kleine ondernemers een kans hebben.",
    "themas": ["Winkels"],
    "ambassadeurs": 1,
    "helpers": 6,
    "steuners": 22,
  },
  {
    "id": 6,
    "afbeelding": "",
    "titel": "Goede connectie ov",
    "omschrijving": "Het zou fijn zijn als we vanaf heel Strandeiland goede ov verbindingen hebben naar de rest van Amsterdam. Op die manier stimuleren we duurzaam vervoer in plaats van de auto.",
    "themas": ["Infrastructuur"],
    "ambassadeurs": 1,
    "helpers": 3,
    "steuners": 12,
  },
  {
    "id": 1,
    "afbeelding": "",
    "titel": "Genoeg bankjes op het strand",
    "omschrijving": "Ik wil graag genoeg bankjes op het strand zodat ik lekker kan zitten en kijken naar hoe mijn kleinkinderen aan het spelen en dollen zijn op het strand. Eventueel zouden picknicktafels ook een goede optie zijn zodat we ook een plek hebben om ergens te zitten en te lunchen",
    "themas": ["Natuur", "Infrastructuur"],
    "ambassadeurs": 2,
    "helpers": 7,
    "steuners": 26,
  },
  {
    "id": 2,
    "afbeelding": "",
    "titel": "Bewakingscamera's rondom Strandeiland",
    "omschrijving": "In verband met veiligheid lijkt het ons fijn als er meerdere bewakingscamera's op Strandeiland zijn.",
    "themas": ["Veiligheid"],
    "ambassadeurs": 0,
    "helpers": 1,
    "steuners": 4,
  },
  {
    "id": 3,
    "afbeelding": "",
    "titel": "Buurthuis voor ouderen",
    "omschrijving": "Het zou fijn zijn als er een buurthuis komt voor ouderen (en jongeren?) om eenzaamheid te bestrijden. Op die manier hebben we contact met de bewoners van Strandeiland en kunnen we meer verbondenheid krijgen",
    "themas": ["Recreatie"],
    "ambassadeurs": 3,
    "helpers": 4,
    "steuners": 15,
  },
  {
    "id": 4,
    "afbeelding": "",
    "titel": "Kinderen leren milieu te beschermen",
    "omschrijving": "Een lesplan voor basisscholen, zodat jonge kinderen al leren om zwerfafval op te ruimen",
    "themas": ["Onderwijs", "Jeugd", "Milieu"],
    "ambassadeurs": 4,
    "helpers": 10,
    "steuners": 31,
  },
  {
    "id": 5,
    "afbeelding": "",
    "titel": "Kleine ondernemers",
    "omschrijving": "Het zou fijn zijn als er betaalbare winkelpanden komen zodat ook de kleine ondernemers een kans hebben.",
    "themas": ["Winkels"],
    "ambassadeurs": 1,
    "helpers": 6,
    "steuners": 22,
  },
  {
    "id": 6,
    "afbeelding": "",
    "titel": "Goede connectie ov",
    "omschrijving": "Het zou fijn zijn als we vanaf heel Strandeiland goede ov verbindingen hebben naar de rest van Amsterdam. Op die manier stimuleren we duurzaam vervoer in plaats van de auto.",
    "themas": ["Infrastructuur"],
    "ambassadeurs": 1,
    "helpers": 3,
    "steuners": 12,
  },
  {
    "id": 1,
    "afbeelding": "",
    "titel": "Genoeg bankjes op het strand",
    "omschrijving": "Ik wil graag genoeg bankjes op het strand zodat ik lekker kan zitten en kijken naar hoe mijn kleinkinderen aan het spelen en dollen zijn op het strand. Eventueel zouden picknicktafels ook een goede optie zijn zodat we ook een plek hebben om ergens te zitten en te lunchen",
    "themas": ["Natuur", "Infrastructuur"],
    "ambassadeurs": 2,
    "helpers": 7,
    "steuners": 26,
  },
  {
    "id": 2,
    "afbeelding": "",
    "titel": "Bewakingscamera's rondom Strandeiland",
    "omschrijving": "In verband met veiligheid lijkt het ons fijn als er meerdere bewakingscamera's op Strandeiland zijn.",
    "themas": ["Veiligheid"],
    "ambassadeurs": 0,
    "helpers": 1,
    "steuners": 4,
  },
  {
    "id": 3,
    "afbeelding": "",
    "titel": "Buurthuis voor ouderen",
    "omschrijving": "Het zou fijn zijn als er een buurthuis komt voor ouderen (en jongeren?) om eenzaamheid te bestrijden. Op die manier hebben we contact met de bewoners van Strandeiland en kunnen we meer verbondenheid krijgen",
    "themas": ["Recreatie"],
    "ambassadeurs": 3,
    "helpers": 4,
    "steuners": 15,
  },
  {
    "id": 4,
    "afbeelding": "",
    "titel": "Kinderen leren milieu te beschermen",
    "omschrijving": "Een lesplan voor basisscholen, zodat jonge kinderen al leren om zwerfafval op te ruimen",
    "themas": ["Onderwijs", "Jeugd", "Milieu"],
    "ambassadeurs": 4,
    "helpers": 10,
    "steuners": 31,
  },
  {
    "id": 5,
    "afbeelding": "",
    "titel": "Kleine ondernemers",
    "omschrijving": "Het zou fijn zijn als er betaalbare winkelpanden komen zodat ook de kleine ondernemers een kans hebben.",
    "themas": ["Winkels"],
    "ambassadeurs": 1,
    "helpers": 6,
    "steuners": 22,
  },
  {
    "id": 6,
    "afbeelding": "",
    "titel": "Goede connectie ov",
    "omschrijving": "Het zou fijn zijn als we vanaf heel Strandeiland goede ov verbindingen hebben naar de rest van Amsterdam. Op die manier stimuleren we duurzaam vervoer in plaats van de auto.",
    "themas": ["Infrastructuur"],
    "ambassadeurs": 1,
    "helpers": 3,
    "steuners": 12,
  },
  {
    "id": 1,
    "afbeelding": "",
    "titel": "Genoeg bankjes op het strand",
    "omschrijving": "Ik wil graag genoeg bankjes op het strand zodat ik lekker kan zitten en kijken naar hoe mijn kleinkinderen aan het spelen en dollen zijn op het strand. Eventueel zouden picknicktafels ook een goede optie zijn zodat we ook een plek hebben om ergens te zitten en te lunchen",
    "themas": ["Natuur", "Infrastructuur"],
    "ambassadeurs": 2,
    "helpers": 7,
    "steuners": 26,
  },
  {
    "id": 2,
    "afbeelding": "",
    "titel": "Bewakingscamera's rondom Strandeiland",
    "omschrijving": "In verband met veiligheid lijkt het ons fijn als er meerdere bewakingscamera's op Strandeiland zijn.",
    "themas": ["Veiligheid"],
    "ambassadeurs": 0,
    "helpers": 1,
    "steuners": 4,
  },
  {
    "id": 3,
    "afbeelding": "",
    "titel": "Buurthuis voor ouderen",
    "omschrijving": "Het zou fijn zijn als er een buurthuis komt voor ouderen (en jongeren?) om eenzaamheid te bestrijden. Op die manier hebben we contact met de bewoners van Strandeiland en kunnen we meer verbondenheid krijgen",
    "themas": ["Recreatie"],
    "ambassadeurs": 3,
    "helpers": 4,
    "steuners": 15,
  },
  {
    "id": 4,
    "afbeelding": "",
    "titel": "Kinderen leren milieu te beschermen",
    "omschrijving": "Een lesplan voor basisscholen, zodat jonge kinderen al leren om zwerfafval op te ruimen",
    "themas": ["Onderwijs", "Jeugd", "Milieu"],
    "ambassadeurs": 4,
    "helpers": 10,
    "steuners": 31,
  },
  {
    "id": 5,
    "afbeelding": "",
    "titel": "Kleine ondernemers",
    "omschrijving": "Het zou fijn zijn als er betaalbare winkelpanden komen zodat ook de kleine ondernemers een kans hebben.",
    "themas": ["Winkels"],
    "ambassadeurs": 1,
    "helpers": 6,
    "steuners": 22,
  },
  {
    "id": 6,
    "afbeelding": "",
    "titel": "Goede connectie ov",
    "omschrijving": "Het zou fijn zijn als we vanaf heel Strandeiland goede ov verbindingen hebben naar de rest van Amsterdam. Op die manier stimuleren we duurzaam vervoer in plaats van de auto.",
    "themas": ["Infrastructuur"],
    "ambassadeurs": 1,
    "helpers": 3,
    "steuners": 12,
  },
];

export default wensen;